webtalk_init -webtalk_dir /media/jeffee/T7/vivado/ripple_carry_adder/ripple_carry_adder.sim/sim_1/behav/xsim/xsim.dir/ripple_carry_adder_Nb_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 24 16:07:44 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c431cc91-d683-4fe7-a509-4076b6f19322" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "887b02798bef49158d0e82ca4c8a7479" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126084_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1914591476 -regid "" -xml /media/jeffee/T7/vivado/ripple_carry_adder/ripple_carry_adder.sim/sim_1/behav/xsim/xsim.dir/ripple_carry_adder_Nb_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/jeffee/T7/vivado/ripple_carry_adder/ripple_carry_adder.sim/sim_1/behav/xsim/xsim.dir/ripple_carry_adder_Nb_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/jeffee/T7/vivado/ripple_carry_adder/ripple_carry_adder.sim/sim_1/behav/xsim/xsim.dir/ripple_carry_adder_Nb_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
