# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq-z2.xdc

# Block Designs: bd/uart/uart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart || ORIG_REF_NAME==uart} -quiet] -quiet

# IP: bd/uart/ip/uart_Debounce_Switch_0_0/uart_Debounce_Switch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_Debounce_Switch_0_0 || ORIG_REF_NAME==uart_Debounce_Switch_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_uart_top_sub_0_0/uart_uart_top_sub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_uart_top_sub_0_0 || ORIG_REF_NAME==uart_uart_top_sub_0_0} -quiet] -quiet

# XDC: bd/uart/uart_ooc.xdc
